[package]
name = "gearly-parts"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
diesel = { version = "2.3.11", features = ["mysql", "chrono"] }
dotenv = "0.15.0"
reqwest = { version = "0.13.4", features = ["json"] }
jsonwebtoken = { version = "11.0.0", features = ["aws_lc_rs"]}
chrono = "0.4.45"
serde = "1.0.229"
